# Generated by Django 2.0 on 2018-01-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='record create time')),
                ('modidy_time', models.DateTimeField(auto_now=True, verbose_name='record latest modify time')),
                ('remark', models.CharField(max_length=64, verbose_name='remark about this record')),
                ('mall', models.CharField(max_length=64, verbose_name='所属商场id')),
                ('floor', models.CharField(max_length=64, verbose_name='所属楼层')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='商铺名称')),
                ('brief', models.CharField(default='', max_length=256, verbose_name='商铺简介')),
                ('desc', models.TextField(default='', verbose_name='详细描述')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
